import Vue from 'vue'

<template>
    <div v-if="Object.keys(task).length !== 0" class="taskDetail">
        <div v-if="Object.keys(task).length !== 0" class="taskName">
                <b>{{ task.name }}</b>
        </div>

        <div class="taskNote" v-if="Object.keys(task).length !== 0">
                <div class="noteDisplay" v-html="markedNote"></div>
        </div>
        <div class="timers">#sessions: {{numberOfSessions}} | total time: {{[totalTimeSpent, 'seconds'] | duration().hours()}}h{{[totalTimeSpent, 'seconds'] | duration().minutes()}}m</div>
    </div>
</template>

<script>
  // Markdown transformer
  let marked = require('marked')
  let renderer = new marked.Renderer()

  // Make all links generated by marked open in new window
  renderer.link = function (href, title, text) {
    return '<a target="_blank" href="' + href + '" title="' + title + '">' + text + '</a>'
  }

  export default {
    name: 'ArchivedTaskDetail',
    components: {},
    props: {
      task: {
        type: Object,
        required: true
      }
    },
    computed: {
      markedNote: function () {
        if (this.task.note) {
          return marked(this.task.note, {renderer: renderer})
        }
      },
      totalTimeSpent: function () {
        if (this.task.totalTimeSpent) {
          return this.task.totalTimeSpent
        } else {
          return 0
        }
      },
      numberOfSessions: function () {
        if (this.task.numberOfSessions) {
          return this.task.numberOfSessions
        } else {
          return 0
        }
      }
    },
    methods: {
      averageTimePerSession: function () {
        if (this.numberOfSessions === 0) {
          return 0
        } else {
          return this.totalTimeSpent / this.numberOfSessions
        }
      }
    }
  }
</script>

<style scoped>

    .taskDetail {
        grid-area: taskDetail;
        display: grid;
        grid-template-rows: 40px 1fr;
        grid-template-columns: 1fr;
        grid-template-areas:    "taskName"
        "taskNote"
        "timers";
        grid-row-gap: 10px;
        background-color: lightgrey;
        margin-right: 50px;
        padding: 20px;
    }

    .taskName {
        grid-area: taskName;
        display: grid;
        grid-auto-flow: column;
        overflow: auto;
    }

    .taskNote {
        grid-area: taskNote;
    }

    .noteDisplay {
        width: 80%;
        font-family: 'Raleway';
        font-style: normal;
        font-weight: 500;
        font-size: 10pt;
        -webkit-font-smoothing: antialiased;
    }

    .timers {
        display: grid;
        grid-area: timers;
        font-size: 9pt;
        font-weight: lighter;
        justify-content: center;
    }

</style>