<template>
    <div id="mainPage">
        <div class="header">
            <div></div>
            <font-awesome-icon v-tooltip.left="{content:'leave focus mode', class:'tooltip close', delay: 50}" icon="times" @click="goBack"/>
        </div>
        <div class="content">
            <div class="timers">#sessions: {{numberOfSessions}} | total time: {{totalTimeSpent}} | this session: {{totalSessionSeconds}}</div>
            <div class="name">{{task.name }}</div>
            <div class="note" v-html="markedNote"></div>
        </div>
    </div>
</template>

<script>
  import Planntt from '../App'
  import FontAwesomeIcon from '@fortawesome/vue-fontawesome'

  // Markdown transformer
  let marked = require('marked')
  let renderer = new marked.Renderer()

  // Make all links generated by marked open in new window
  renderer.link = function (href, title, text) {
    return '<a target="_blank" href="' + href + '" title="' + title + '">' + text + '</a>'
  }

  export default {
    name: 'FocusTask',
    components: {
      FontAwesomeIcon, Planntt
    },
    props: {
      task: {
        type: Object,
        required: true
      }
    },
    data () {
      return {
        sessionSeconds: 0,
        interval: null
      }
    },
    mounted () {

    },
    created () {
      this.interval = setInterval(() => ++this.sessionSeconds, 1000)
      document.addEventListener('keydown', this.escapeHandler)
      if (!this.task.numberOfSessions) {
        this.task.numberOfSessions = 1
      } else {
        this.task.numberOfSessions += 1
      }
    },
    destroyed () {
      clearInterval(this.interval)
      document.removeEventListener('keydown', this.escapeHandler)
    },
    methods: {
      averageTimePerSession: function () {
        return this.totalTimeSpent / this.numberOfSessions
      },
      escapeHandler: function (event) {
        event.stopImmediatePropagation()
        console.log('executing event listener')
        if (event.key === 'Escape' || event.keyCode === 27) {
          this.goBack()
        }
      },
      goBack: function () {
        if (!this.task.totalTimeSpent) {
          this.task.totalTimeSpent = this.sessionSeconds
        } else {
          this.task.totalTimeSpent += this.sessionSeconds
        }
        this.updateFocusedTime(this.sessionSeconds)
        this.$taskDb.update({id: this.task.id}, this.task, {})
        console.log('added ' + this.sessionSeconds + ' seconds to make the total ' + this.task.totalTimeSpent)
        this.$router.push('/')
      },
      updateFocusedTime: function (sessionSeconds) {
        // Update Vue store:
        this.$store.commit('addFocusedTimeToday', sessionSeconds)
        // Add it to the file-based storage:
        const currentTodayFocusedTime = this.$store.getters.getFocusedTimeToday
        console.log('when updating this is current today focused time: ' + currentTodayFocusedTime)
        const today = this.$moment().format('YYYY-MM-DD')
        this.$focusedTime.update({date: today}, {date: today, timeInSeconds: currentTodayFocusedTime}, {upsert: true})
      }
    },
    computed: {
      totalTimeSpent: function () {
        let totalTimeSpent = 0
        if (this.task.totalTimeSpent) {
          totalTimeSpent = this.task.totalTimeSpent
        }
        totalTimeSpent += this.sessionSeconds
        const hours = Math.floor(totalTimeSpent / 3600)
        const minutes = Math.floor((totalTimeSpent - (hours * 3600)) / 60)
        const seconds = totalTimeSpent - (hours * 3600) - (minutes * 60)
        return hours + 'h:' + minutes + 'm:' + seconds + 's'
      },
      totalSessionSeconds: function () {
        let totalTimeSpent = 0
        if (this.sessionSeconds) {
          totalTimeSpent = this.sessionSeconds
        }
        const hours = Math.floor(totalTimeSpent / 3600)
        const minutes = Math.floor((totalTimeSpent - (hours * 3600)) / 60)
        const seconds = totalTimeSpent - (hours * 3600) - (minutes * 60)
        return hours + 'h:' + minutes + 'm:' + seconds + 's'
      },
      numberOfSessions: function () {
        if (this.task.numberOfSessions) {
          return this.task.numberOfSessions
        } else {
          return 1
        }
      },
      markedNote: function () {
        if (this.task.note) {
          return marked(this.task.note, {renderer: renderer})
        }
      }
    }
  }
</script>

<style scoped>

    #mainPage {
        font-family: 'Raleway';
        font-style: normal;
        font-weight: 500;
        font-size: 10pt;
        -webkit-font-smoothing: antialiased;
    }

    .header {
        display: grid;
        grid-area: header;
        grid-template-rows: 1fr;
        grid-template-columns: 1fr 10px;
        grid-template-areas: ". close";
        margin-right: 10px;
        margin-top: 10px;
    }

    .close {
        display: grid;
        color: gray;
    }

    .content {
        display: grid;
        grid-area: content;
        grid-template-rows: 100px 200px 1fr;
        grid-template-columns: 1fr;
        grid-template-areas: "timers"
        "name"
        "note";
    }

    .timers {
        display: grid;
        grid-area: timers;
        font-size: 9pt;
        font-weight: lighter;
        justify-content: center;
    }

    .name {
        display: grid;
        grid-area: name;
        margin: 50px 100px;
        font-size: 50pt;
        font-weight: bold;
        justify-content: center;
    }

    .note {
        display: grid;
        grid-area: note;
        margin: 50px;
        font-size: 20pt;
        justify-content: center;
    }

    ul {
        padding-left: 1em;
        line-height: 1.5em;
        list-style-type: dot;
        margin-bottom: 1em;
    }

    li {
        list-style: none;
    }


</style>