<template>
    <div id="mainPage">
        <div class="header">
            <div></div>
            <router-link class="close" to="/"><font-awesome-icon v-tooltip.left="{content:'leave focus mode', class:'tooltip', delay: 50}" icon="times"/></router-link>
        </div>
        <div class="content">
            <div class="name">{{task.name }}</div>
            <div class="note" v-html="markedNote"></div>
        </div>
    </div>
</template>

<script>
  import Planntt from '../App'
  import FontAwesomeIcon from '@fortawesome/vue-fontawesome'

  // Markdown transformer
  let marked = require('marked')
  let renderer = new marked.Renderer()

  // Make all links generated by marked open in new window
  renderer.link = function (href, title, text) {
    return '<a target="_blank" href="' + href + '" title="' + title + '">' + text + '</a>'
  }

  export default {
    name: 'FocusTask',
    components: {
      FontAwesomeIcon, Planntt
    },
    props: {
      task: {
        type: Object,
        required: true
      }
    },
    data () {
      return {
        timer: 0
      }
    },
    created () {
    },
    methods: {
    },
    computed: {
      markedNote: function () {
        if (this.task.note) {
          return marked(this.task.note, {renderer: renderer})
        }
      }
    }
  }
</script>

<style scoped>

    #mainPage {
        font-family: 'Raleway';
        font-style: normal;
        font-weight: 500;
        font-size: 10pt;
        -webkit-font-smoothing: antialiased;
    }

    .header {
        display: grid;
        grid-area: header;
        grid-template-rows: 1fr;
        grid-template-columns: 1fr 10px;
        grid-template-areas: ". close";
    }

    .close {
        display: grid;
        color: gray;
    }

    .content {
        display: grid;
        grid-area: content;
        grid-template-rows: 200px 1fr;
        grid-template-columns: 1fr;
        grid-template-areas: "name"
        "note";
    }

    .name {
        display: grid;
        grid-area: name;
        margin: 50px 100px;
        font-size: 50pt;
        font-weight: bold;
        justify-content: center;
    }

    .note {
        display: grid;
        grid-area: note;
        margin: 50px;
        font-size: 20pt;
        justify-content: center;
    }

    ul {
        padding-left: 1em;
        line-height: 1.5em;
        list-style-type: dot;
        margin-bottom: 1em;
    }

    li {
        list-style: none;
    }


</style>