import Vue from 'vue'

<template>
    <div v-if="Object.keys(journalEntry).length !== 0" class="journalEntryDetail">
        <div v-if="Object.keys(journalEntry).length !== 0" class="editJournalEntry">
            <div class="editJournalEntryFirstPart">
                <div v-show="!editingJournalEntryName" class="journalEntryNameToEdit">
                    <font-awesome-icon v-tooltip.top="{content:'close detail (ESC)', class:'tooltip', delay: 50}" @click="closeDetail" icon="times" class="iconCloseDetail"/>
                    <b>{{ journalEntry.name }}</b>
                    <font-awesome-icon v-tooltip.top="{content:'edit journal entry name', class:'tooltip', delay: 50}"
                                       @click="startEditJournalEntryName" icon="pencil-alt"
                                       class="iconJournalEntryNameToEdit"/>
                </div>
                <input v-show="editingJournalEntryName"
                       type="text"
                       class="inputJournalEntryNameToEdit"
                       v-model="journalEntry.name"
                       @blur="doneEditJournalEntryName"
                       @keyup.enter="doneEditJournalEntryName"
                       @keyup.esc="cancelEditJournalEntryName"
                       @focus="$event.target.select()"
                       v-focus="editingJournalEntryName"/>
            </div>
        </div>

        <div v-if="Object.keys(journalEntry).length !== 0" class="whenChoices">
            <date-picker class="whenChoiceSpecific" lang="en" @change="changeDate" placeholder="journal date" v-model="journalEntry.journalDate" :first-day-of-week="1"></date-picker>
        </div>

        <button v-if="Object.keys(journalEntry).length !== 0" v-show="!editingNote && !journalEntry.note" class="is-active addNote" @click="startEditNote">
            add note
        </button>

        <div v-show="editingNote" class="controlsLine">
            <div class="editNoteControls">
                <button @click="doneEditNote" class="is-active">save</button>
                <button @click="cancelEditNote">cancel</button>
                <button @click="deleteEditNote">delete</button>
            </div>
        </div>
        <div v-show="!editingNote" class="controlsLine">
            <div class="editNoteControls">
                <button v-show="journalEntry.note" class="is-active" @click="startEditNote">
                    edit note
                </button>
            </div>
        </div>

        <div class="journalEntryNote" v-if="Object.keys(journalEntry).length !== 0">
                <div v-show="!editingNote" class="noteDisplay" v-html="markedNote"></div>
                <div v-show="editingNote">
                    <textarea class="noteInput" placeholder="add your note here" v-model="journalEntry.note"></textarea>
                </div>
        </div>
        <div class="timers">created: {{ journalEntry.created | moment("YYYY-MM-DD hh:mma")}}
        </div>
    </div>
</template>

<script>
  import FontAwesomeIcon from '@fortawesome/vue-fontawesome'
  import DatePicker from 'vue2-datepicker'

  // Markdown transformer
  let marked = require('marked')
  let renderer = new marked.Renderer()

  // Make all links generated by marked open in new window
  renderer.link = function (href, title, text) {
    return '<a target="_blank" href="' + href + '" title="' + title + '">' + text + '</a>'
  }

  export default {
    name: 'JournalEntryDetail',
    components: {FontAwesomeIcon, DatePicker},
    props: {
      journalEntry: {
        type: Object,
        required: true
      }
    },
    data: function () {
      return {
        editingJournalEntryName: false
      }
    },
    computed: {
      editingNote: function () {
        return this.$store.getters.isEditingJournalNote
      },
      markedNote: function () {
        if (this.journalEntry.note) {
          return marked(this.journalEntry.note, {renderer: renderer})
        }
      }
    },
    filters: {
    },
    methods: {
      changeDate: function (currentValue) {
        this.saveJournalEntry()
      },
      closeDetail: function () {
        this.$emit('closeDetail', this.journalEntry)
      },
      startEditJournalEntryName: function () {
        console.log('starting to edit journalEntry name: ' + this.journalEntry.name)
        this.journalEntryNameBeforeEdit = this.journalEntry.name
        this.editingJournalEntryName = true
      },
      doneEditJournalEntryName: function () {
        if (!this.editingJournalEntryName) {
          return
        }
        this.journalEntry.name = this.journalEntry.name.trim()
        if (!this.journalEntry.name) {
          this.cancelEditJournalEntryName()
        }
        this.editingJournalEntryName = false
        this.journalEntryNameBeforeEdit = null
        this.saveJournalEntry()
      },
      cancelEditJournalEntryName: function () {
        console.log('text before editing: ' + this.journalEntryNameBeforeEdit)
        this.journalEntry.name = this.journalEntryNameBeforeEdit
        this.journalEntryNameBeforeEdit = null
        this.editingJournalEntryName = false
      },
      startEditNote: function () {
        console.log('starting to edit note')
        this.noteBeforeEdit = this.journalEntry.note
        this.$store.commit('setEditingJournalNote', true)
      },
      doneEditNote: function () {
        console.log('done to edit note')
        this.$store.commit('setEditingJournalNote', false)
        this.noteBeforeEdit = null
        this.saveJournalEntry()
      },
      cancelEditNote: function () {
        console.log('cancel edit note')
        this.journalEntry.note = this.noteBeforeEdit
        this.noteBeforeEdit = null
        this.$store.commit('setEditingJournalNote', false)
      },
      deleteEditNote: function () {
        console.log('delete edit note')
        this.journalEntry.note = null
        this.saveJournalEntry()
        this.$store.commit('setEditingJournalNote', false)
      },
      saveJournalEntry: function () {
        this.$journal.update({id: this.journalEntry.id}, this.journalEntry, {})
      },
      // https://stackoverflow.com/questions/105034/create-guid-uuid-in-javascript
      uuidv4: function () {
        return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function (c) {
          let r = Math.random() * 16 | 0
          let v = c === 'x' ? r : (r & 0x3 | 0x8)
          return v.toString(16)
        })
      }
    },
    // https://vuejs.org/v2/guide/custom-directive.html
    directives: {
      focus: function (el, binding) {
        if (binding.value) {
          el.focus()
        }
      }
    }
  }
</script>

<style scoped>

    .journalEntryDetail {
        display: flex;
        flex-direction: column;
        margin-right: 50px;
        margin-top: 50px;
        padding-top: 10px;
        border-top: 1px solid;
        border-top-color: rgb(220, 220, 222);
        flex: 1 1 auto;
    }

    .is-active {
        text-decoration: underline;
        cursor:pointer;
        color: forestgreen;
    }

    .editJournalEntry {
        grid-area: editJournalEntry;
        display: grid;
        grid-template-rows: 1fr;
        grid-template-columns: 1fr 1fr;
        grid-template-areas:    "editJournalEntryFirstPart .";
    }

    .editJournalEntryFirstPart {
        grid-area: editJournalEntryFirstPart;
        display: grid;
    }

    .editJournalEntryCreatedDate {
        grid-area: editJournalEntryCreatedDate;
        display: grid;
    }

    .journalEntryNameToEdit {
    }

    .inputJournalEntryNameToEdit {
    }

    .inputJournalEntryNameToEdit:focus {
        outline-color: #4AD94A;
    }

    .iconJournalEntryNameToEdit {
        margin-left: 5px;
    }

    .iconCloseDetail {
        margin-right: 5px;
    }

    .whenChoices {
        grid-area: whenChoices;
        display: grid;
        grid-template-columns: 1fr;
        grid-template-areas:    "whenChoiceSpecific";
        align-items: center;
        margin-top: 20px;
    }

    .whenChoiceSpecific {
        grid-area: whenChoiceSpecific;
        justify-self: end;
    }

    .addNote {
        grid-area: addNote;
    }

    .journalEntryNote {
        grid-area: journalEntryNote;
        position: relative;
        overflow: auto;
        display: flex;
        flex-direction: column;
        flex: 1 1 auto;
        padding-top: 0;
    }

    .noteDisplay {
        width: 100%;
        font-family: 'Raleway';
        font-style: normal;
        font-weight: 500;
        font-size: 10pt;
        -webkit-font-smoothing: antialiased;
        overflow: auto;
        height: 15vh;
    }

    .noteInput {
        width: 99%;
        height: 15vh;
        margin-top: 10px;
        font-family: 'Raleway';
        font-style: normal;
        font-weight: 500;
        font-size: 10pt;
        -webkit-font-smoothing: antialiased;
    }

    .controlsLine {
        display: flex;
        flex-direction: row;
        justify-content: flex-start;
        margin-top: 10px;
    }

    .editNoteControls {
    }

    input {
        font: inherit;
    }

    input::selection {
        background-color: #4AD94A;
    }

    textarea {
        font: inherit;
    }

    textarea:focus {
        outline-color: #4AD94A;
    }

    button {
        background-color: black;
        outline: 0;
        border: none;
        color: white;
        font-family: 'Roboto Mono';
        font-style: normal;
        font-weight: 500;
        width: 100px;
        height: 25px;
        line-height: 25px;
        text-transform: uppercase;
        border-radius: 2px;
        text-align: center;
        letter-spacing: 0.5px;
        cursor: pointer;
        transition: .3s ease-out;
        font-size: 12px;
    }

    button.is-active {
        text-decoration: none;
        color: white;
        background-color: forestgreen;
    }

    .timers {
        display: grid;
        grid-area: timers;
        font-size: 9pt;
        justify-content: center;
    }

</style>
