import Vue from 'vue'

<template>
    <div v-if="Object.keys(task).length !== 0" class="taskDetail">
        <div v-if="Object.keys(task).length !== 0" class="editTask">
            <div class="editTaskFirstPart">
                <div v-show="!editingTaskName" class="taskNameToEdit">
                    <b>{{ task.name }}</b>
                    <font-awesome-icon v-tooltip.top="{content:'edit task name', class:'tooltip', delay: 50}"
                                       @click="startEditTaskName" icon="pencil-alt"
                                       class="iconTaskNameToEdit"/>
                </div>
                <input v-show="editingTaskName"
                       type="text"
                       class="inputTaskNameToEdit"
                       v-model="task.name"
                       @blur="doneEditTaskName"
                       @keyup.enter="doneEditTaskName"
                       @keyup.esc="cancelEditTaskName"
                       @focus="$event.target.select()"
                       v-focus="editingTaskName"/>
            </div>
            <div class="taskIcons">
                <font-awesome-icon v-tooltip.top="{content:'duplicate task', class:'tooltip', delay: 50}" @click="duplicateTask" icon="clone" class="iconDuplicateTask"/>
                <font-awesome-icon v-tooltip.top="{content:'(un)block task', class:'tooltip', delay: 50}" @click="blockTask" icon="ban" :class="{'blocked': blocked, 'notBlocked': !blocked}"/>
                <font-awesome-icon v-tooltip.top="{content:'show project', class:'tooltip', delay: 50}" @click="expandProject" icon="crosshairs"/>
                <router-link class="focusTask" :to="{ name: 'focusTask', params: { task } }"><font-awesome-icon v-tooltip.top="{content:'focus mode', class:'tooltip', delay: 50}" icon="headphones"/></router-link>
            </div>
        </div>

        <div v-if="Object.keys(task).length !== 0" class="whenChoices">
            <a @click="setWhen('today')" :class="{'is-active': task.when === 'today'}" class="whenChoice whenChoiceToday">
                today</a>
            <a @click="setWhen('thisweek')" :class="{'is-active': task.when === 'thisweek'}" class="whenChoice whenChoiceThisWeek">
                this week</a>
            <a @click="setWhen('waitingfor')" :class="{'is-active': task.when === 'waitingfor'}" class="whenChoice whenChoiceWaitingFor">
                waiting for</a>
            <a @click="setWhen('someday')" :class="{'is-active': task.when === 'someday'}" class="whenChoice whenChoiceSomeday">
                someday</a>
            <date-picker class="whenChoiceSpecific" lang="en" @change="changeDate" placeholder="due date" v-model="task.due" :first-day-of-week="1"></date-picker>
        </div>

        <button v-if="Object.keys(task).length !== 0" v-show="!editingNote && !task.note" class="is-active addNote" @click="startEditNote">
            add note
        </button>

        <div v-show="editingNote" class="controlsLine">
            <div class="editNoteControls">
                <button @click="doneEditNote" class="is-active">save</button>
                <button @click="cancelEditNote">cancel</button>
                <button @click="deleteEditNote">delete</button>
            </div>
        </div>
        <div v-show="!editingNote" class="controlsLine">
            <div class="editNoteControls">
                <button v-show="task.note" class="is-active" @click="startEditNote">
                    edit note
                </button>
            </div>
        </div>

        <div class="taskNote" v-if="Object.keys(task).length !== 0">
                <div v-show="!editingNote" class="noteDisplay" v-html="markedNote"></div>
                <div v-show="editingNote">
                    <textarea class="noteInput" placeholder="add your note here" v-model="task.note"></textarea>
                </div>
        </div>
        <div class="timers">#sessions: {{numberOfSessions}} | total time: {{prettyTotalTimeSpent}}  | created: {{ task.created | moment("YYYY-MM-DD hh:mma")}}
        </div>
    </div>
</template>

<script>
  import FontAwesomeIcon from '@fortawesome/vue-fontawesome'
  import DatePicker from 'vue2-datepicker'

  // Markdown transformer
  let marked = require('marked')
  let renderer = new marked.Renderer()

  // Make all links generated by marked open in new window
  renderer.link = function (href, title, text) {
    return '<a target="_blank" href="' + href + '" title="' + title + '">' + text + '</a>'
  }

  export default {
    name: 'TaskDetail',
    components: {FontAwesomeIcon, DatePicker},
    props: {
      task: {
        type: Object,
        required: true
      }
    },
    data: function () {
      return {
        editingTaskName: false,
        editingNote: false
      }
    },
    computed: {
      blocked: function () {
        return !!this.task.blocked
      },
      selectedProject: function () {
        return this.$store.getters.getSelectedProject
      },
      selectedProjectName: function () {
        return this.$store.getters.getSelectedProjectName
      },
      prettyTotalTimeSpent: function () {
        let totalTimeSpent = 0
        if (this.task.totalTimeSpent) {
          totalTimeSpent = this.task.totalTimeSpent
        }
        const hours = Math.floor(totalTimeSpent / 3600)
        const minutes = Math.floor((totalTimeSpent - (hours * 3600)) / 60)
        const seconds = totalTimeSpent - (hours * 3600) - (minutes * 60)
        return hours + 'h:' + minutes + 'm:' + seconds + 's'
      },
      numberOfSessions: function () {
        if (this.task.numberOfSessions) {
          return this.task.numberOfSessions
        } else {
          return 0
        }
      },
      markedNote: function () {
        if (this.task.note) {
          return marked(this.task.note, {renderer: renderer})
        }
      }
    },
    filters: {
      prettyWhen: function (n) {
        if (n === 'today') {
          return 'Today'
        }
        if (n === 'thisweek') {
          return 'This Week'
        }
        if (n === 'waitingfor') {
          return 'Waiting For'
        }
        if (n === 'someday') {
          return 'Someday'
        }
      }
    },
    methods: {
      expandProject: function () {
        this.$store.commit('setPathFromRootToProjectExpanded', this.task.project)
      },
      averageTimePerSession: function () {
        if (this.numberOfSessions === 0) {
          return 0
        } else {
          return this.totalTimeSpent / this.numberOfSessions
        }
      },
      changeDate: function (currentValue) {
        this.saveTask()
      },
      setWhen: function (when) {
        console.log('setting task to when: ' + when)
        this.task.when = when
        this.saveTask()
      },
      duplicateTask: function () {
        this.$emit('duplicateTask', this.task)
      },
      blockTask: function () {
        let currentBlock = this.task.blocked
        if (currentBlock) {
          console.log('unblocking task: ' + this.task.name)
          this.$set(this.task, 'blocked', false)
        } else {
          console.log('blocking task: ' + this.task.name)
          this.$set(this.task, 'blocked', true)
        }
        this.saveTask()
      },
      startEditTaskName: function () {
        console.log('starting to edit task name: ' + this.task.name)
        this.taskNameBeforeEdit = this.task.name
        this.editingTaskName = true
      },
      doneEditTaskName: function () {
        if (!this.editingTaskName) {
          return
        }
        this.task.name = this.task.name.trim()
        if (!this.task.name) {
          this.cancelEditTaskName()
        }
        this.editingTaskName = false
        this.taskNameBeforeEdit = null
        this.saveTask()
      },
      cancelEditTaskName: function () {
        console.log('text before editing: ' + this.taskNameBeforeEdit)
        this.task.name = this.taskNameBeforeEdit
        this.taskNameBeforeEdit = null
        this.editingTaskName = false
      },
      startEditNote: function () {
        console.log('starting to edit note')
        this.noteBeforeEdit = this.task.note
        this.editingNote = true
      },
      doneEditNote: function () {
        console.log('done to edit note')
        this.editingNote = false
        this.noteBeforeEdit = null
        this.saveTask()
      },
      cancelEditNote: function () {
        console.log('cancel edit note')
        this.task.note = this.noteBeforeEdit
        this.noteBeforeEdit = null
        this.editingNote = false
      },
      deleteEditNote: function () {
        console.log('delete edit note')
        this.task.note = null
        this.saveTask()
        this.editingNote = false
      },
      saveTask: function () {
        this.$taskDb.update({id: this.task.id}, this.task, {})
      },
      // https://stackoverflow.com/questions/105034/create-guid-uuid-in-javascript
      uuidv4: function () {
        return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function (c) {
          let r = Math.random() * 16 | 0
          let v = c === 'x' ? r : (r & 0x3 | 0x8)
          return v.toString(16)
        })
      }
    },
    // https://vuejs.org/v2/guide/custom-directive.html
    directives: {
      focus: function (el, binding) {
        if (binding.value) {
          el.focus()
        }
      }
    }
  }
</script>

<style scoped>

    .taskDetail {
        grid-area: taskDetail;
        display: grid;
        grid-template-rows: 20px 30px 20px 1fr 20px;
        grid-template-columns: 1fr;
        grid-template-areas:    "editTask"
        "whenChoices"
        "addNote"
        "taskNote"
        "timers";
        grid-row-gap: 10px;
        background-color: #E0E0E0;
        padding: 20px;
    }

    .whenChoice {
        text-decoration: underline;
        cursor:pointer;
        padding-right: 5px;
    }

    .is-active {
        text-decoration: underline;
        cursor:pointer;
        color: forestgreen;
    }

    .editTask {
        grid-area: editTask;
        display: grid;
        grid-template-rows: 1fr;
        grid-template-columns: 5fr 1fr;
        grid-template-areas:    "editTaskFirstPart taskIcons";
    }

    .editTaskFirstPart {
        grid-area: editTaskFirstPart;
        display: grid;
    }

    .editTaskCreatedDate {
        grid-area: editTaskCreatedDate;
        display: grid;
    }

    .taskNameToEdit {
    }

    .inputTaskNameToEdit {
    }

    .inputTaskNameToEdit:focus {
        outline-color: #4AD94A;
    }

    .iconTaskNameToEdit {
        margin-left: 20px;
    }

    .whenChoices {
        grid-area: whenChoices;
        display: grid;
        grid-template-columns: 50px 70px 80px 70px 1fr;
        grid-template-areas:    "whenChoiceToday whenChoiceThisWeek whenChoiceWaitingFor whenChoiceSomeday whenChoiceSpecific";
        align-items: center;
    }

    .whenChoiceToday {
        grid-area: whenChoiceToday;
    }

    .whenChoiceThisWeek {
        grid-area: whenChoiceThisWeek;
    }

    .whenChoiceWaitingFor {
        grid-area: whenChoiceWaitingFor;
    }

    .whenChoiceSomeday {
        grid-area: whenChoiceSomeday;
    }

    .whenChoiceSpecific {
        grid-area: whenChoiceSpecific;
        justify-self: end;
    }

    .taskIcons {
        grid-area: taskIcons;
        justify-self: end;
    }

    .addNote {
        grid-area: addNote;
    }

    .taskNote {
        grid-area: taskNote;
    }

    .noteDisplay {
        width: 80%;
        font-family: 'Raleway';
        font-style: normal;
        font-weight: 500;
        font-size: 10pt;
        -webkit-font-smoothing: antialiased;
    }

    .noteInput {
        width: 80%;
        height: 14vh;
        font-family: 'Raleway';
        font-style: normal;
        font-weight: 500;
        font-size: 10pt;
        -webkit-font-smoothing: antialiased;
    }

    .controlsLine {
        width: 80%;
    }

    .editNoteControls {
    }

    .clickable {
        text-decoration: underline;
        cursor:pointer;
        padding-right: 5px;
    }

    input {
        font: inherit;
    }

    input::selection {
        background-color: #4AD94A;
    }

    textarea {
        font: inherit;
    }

    textarea:focus {
        outline-color: #4AD94A;
    }

    button {
        background-color: black;
        outline: 0;
        border: none;
        color: white;
        font-family: 'Roboto Mono';
        font-style: normal;
        font-weight: 500;
        width: 100px;
        height: 25px;
        line-height: 25px;
        text-transform: uppercase;
        border-radius: 2px;
        text-align: center;
        letter-spacing: 0.5px;
        cursor: pointer;
        transition: .3s ease-out;
        font-size: 12px;
    }

    button.is-active {
        text-decoration: none;
        color: white;
        background-color: forestgreen;
    }

    .blocked {
        color: red;
    }

    .notBlocked {
        color: gray;
    }

    .focusTask {
        color: black;
    }

    .timers {
        display: grid;
        grid-area: timers;
        font-size: 9pt;
        justify-content: center;
    }

</style>