import Vue from 'vue'

<template>
    <div>
        <div v-if="task.name">
             <span v-show="!editingTaskName">
                {{ task.name }} &nbsp;</span>
            <input v-show="editingTaskName"
                   type="text"
                   class="input is-rounded"
                   v-model="task.name"
                   @blur="doneEditTaskName"
                   @keyup.enter="doneEditTaskName"
                   @keyup.esc="cancelEditTaskName"
                   @focus="$event.target.select()"
                   v-focus="editingTaskName"/>
            <font-awesome-icon v-show="!editingTaskName" pull="left" @click="startEditTaskName" icon="pencil-alt"/>
        </div>

        <div v-if="task.name" class="whenChoices">
            <a @click="setWhen('today')" :class="{'is-active': task.when === 'today'}" class="whenChoice">
                today
            </a>
            <a @click="setWhen('thisweek')" :class="{'is-active': task.when === 'thisweek'}" class="whenChoice">
                this week
            </a>
            <a @click="setWhen('waitingfor')" :class="{'is-active': task.when === 'waitingfor'}" class="whenChoice">
                waiting for
            </a>
            <a @click="setWhen('someday')" :class="{'is-active': task.when === 'someday'}" class="whenChoice">
                someday
            </a>
        </div>

        <div v-if="task.name">
            <b>Note</b>
            <font-awesome-icon v-show="!editingNote" pull="left" @click="startEditNote" icon="pencil-alt"/>
            <div v-show="!editingNote" v-html="markedNote"></div>
        </div>
        <div v-show="editingNote">
            <a @click="doneEditNote">save</a> |
            <a @click="cancelEditNote">cancel</a>
            <textarea class="textarea" placeholder="add your note here" rows="10" v-model="task.note"></textarea>
        </div>
    </div>
</template>

<script>
  import FontAwesomeIcon from '@fortawesome/vue-fontawesome'

  // Markdown transformer
  let marked = require('marked')
  let renderer = new marked.Renderer()

  // Make all links generated by marked open in new window
  renderer.link = function (href, title, text) {
    return '<a target="_blank" href="' + href + '" title="' + title + '">' + text + '</a>'
  }

  export default {
    name: 'TaskDetail',
    components: {FontAwesomeIcon},
    props: {
      task: {
        type: Object,
        required: true
      }
    },
    data: function () {
      return {
        editingTaskName: false,
        editingNote: false
      }
    },
    computed: {
      selectedProject: function () {
        return this.$store.getters.getSelectedProject
      },
      selectedProjectName: function () {
        return this.$store.getters.getSelectedProjectName
      },
      markedNote: function () {
        if (this.task.note) {
          return marked(this.task.note, {renderer: renderer})
        }
      }
    },
    filters: {
      prettyWhen: function (n) {
        if (n === 'today') {
          return 'Today'
        }
        if (n === 'thisweek') {
          return 'This Week'
        }
        if (n === 'waitingfor') {
          return 'Waiting For'
        }
        if (n === 'someday') {
          return 'Someday'
        }
      }
    },
    methods: {
      setWhen: function (when) {
        console.log('setting task to when: ' + when)
        this.task.when = when
        this.saveTask(this.task)
      },
      startEditTaskName: function () {
        console.log('starting to edit task name: ' + this.task.name)
        this.taskNameBeforeEdit = this.task.name
        this.editingTaskName = true
      },
      doneEditTaskName: function () {
        if (!this.editingTaskName) {
          return
        }
        this.task.name = this.task.name.trim()
        if (!this.task.name) {
          this.cancelEditTaskName()
        }
        this.editingTaskName = false
        this.taskNameBeforeEdit = null
        this.saveTask(this.task)
      },
      cancelEditTaskName: function () {
        this.task.name = this.taskNameBeforeEdit
        this.taskNameBeforeEdit = null
        this.editingTaskName = false
      },
      startEditNote: function () {
        console.log('starting to edit note')
        this.noteBeforeEdit = this.task.note
        this.editingNote = true
        marked('bla')
      },
      doneEditNote: function () {
        console.log('done to edit note')
        this.editingNote = false
        this.noteBeforeEdit = null
        this.saveTask(this.task)
        marked('bla')
      },
      cancelEditNote: function () {
        console.log('cancel edit note')
        this.task.note = this.noteBeforeEdit
        this.noteBeforeEdit = null
        this.editingNote = false
      },
      saveTask: function (task) {
        this.$store.commit('setSelectedTask', this.task)
        // Also save this updated task in the task list
        this.$emit('updateTask', this.task)
      }
    },
    // https://vuejs.org/v2/guide/custom-directive.html
    directives: {
      focus: function (el, binding) {
        if (binding.value) {
          el.focus()
        }
      }
    }
  }
</script>

<style scoped>

    .whenChoice {
        text-decoration: underline;
        cursor:pointer;
        padding-right: 5px;
    }

    .is-active {
        text-decoration: underline;
        cursor:pointer;
        color: forestgreen;
    }

</style>