const { marked } = require('marked')

class MarkdownRenderer {
  /**
   * Create a MarkdownRenderer
   *
   * @constructor
   */
  constructor () {
    this.renderer = new marked.Renderer()

    // Make all links generated by marked open in new window
    this.renderer.link = function (href, title, text) {
      return '<a target="_blank" href="' + href + '" title="' + href + '">' + text + '</a>'
    }
  }

  marked (text) {
    return marked(text, { renderer: this.renderer })
  }
}

export default MarkdownRenderer
